#version 460

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D equirectMap;
layout(set = 0, binding = 1, rgba16f) uniform writeonly image2DArray cubemap;

layout(push_constant) uniform PushConstants {
    uint outputSize;
} push;

const vec2 invAtan = vec2(0.1591, 0.3183);
vec2 sampleSphericalMap(vec3 v) {
    vec2 uv = vec2(atan(v.z, v.x), asin(v.y));
    uv *= invAtan;
    uv += 0.5;
    return uv;
}

vec3 getDirection(uvec3 id, float size) {
    vec2 uv = (vec2(id.xy) + 0.5) / size;
    uv = uv * 2.0 - 1.0;
    
    vec3 dir;
    uint face = id.z;
    if(face == 0) dir = vec3(1.0, -uv.y, -uv.x);      // +X
    else if(face == 1) dir = vec3(-1.0, -uv.y, uv.x); // -X
    else if(face == 2) dir = vec3(uv.x, 1.0, uv.y);   // +Y
    else if(face == 3) dir = vec3(uv.x, -1.0, -uv.y); // -Y
    else if(face == 4) dir = vec3(uv.x, -uv.y, 1.0);  // +Z
    else dir = vec3(-uv.x, -uv.y, -1.0);              // -Z
    
    return normalize(dir);
}

void main() {
    if(gl_GlobalInvocationID.x >= push.outputSize || gl_GlobalInvocationID.y >= push.outputSize) return;
    
    vec3 dir = getDirection(gl_GlobalInvocationID, float(push.outputSize));
    vec2 uv = sampleSphericalMap(dir);
    vec3 color = texture(equirectMap, uv).rgb;
    
    imageStore(cubemap, ivec3(gl_GlobalInvocationID), vec4(color, 1.0));
}
