#version 460

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform samplerCube envMap;
layout(set = 0, binding = 1, rgba16f) uniform writeonly image2DArray irradianceMap;

layout(push_constant) uniform PushConstants {
    uint outputSize;
} push;

const float PI = 3.14159265359;

vec3 getDirection(uvec3 id, float size) {
    vec2 uv = (vec2(id.xy) + 0.5) / size;
    uv = uv * 2.0 - 1.0;
    
    vec3 dir;
    uint face = id.z;
    if(face == 0) dir = vec3(1.0, -uv.y, -uv.x);      // +X
    else if(face == 1) dir = vec3(-1.0, -uv.y, uv.x); // -X
    else if(face == 2) dir = vec3(uv.x, 1.0, uv.y);   // +Y
    else if(face == 3) dir = vec3(uv.x, -1.0, -uv.y); // -Y
    else if(face == 4) dir = vec3(uv.x, -uv.y, 1.0);  // +Z
    else dir = vec3(-uv.x, -uv.y, -1.0);              // -Z
    
    return normalize(dir);
}

void main() {
    if(gl_GlobalInvocationID.x >= push.outputSize || gl_GlobalInvocationID.y >= push.outputSize) return;
    
    vec3 normal = getDirection(gl_GlobalInvocationID, float(push.outputSize));
    vec3 irradiance = vec3(0.0);
    
    vec3 up = abs(normal.z) < 0.999 ? vec3(0.0, 0.0, 1.0) : vec3(1.0, 0.0, 0.0);
    vec3 right = normalize(cross(up, normal));
    up = normalize(cross(normal, right));
    
    float sampleDelta = 0.025;
    float nrSamples = 0.0;
    for(float phi = 0.0; phi < 2.0 * PI; phi += sampleDelta) {
        for(float theta = 0.0; theta < 0.5 * PI; theta += sampleDelta) {
            vec3 tangentSample = vec3(sin(theta) * cos(phi), sin(theta) * sin(phi), cos(theta));
            vec3 sampleVec = tangentSample.x * right + tangentSample.y * up + tangentSample.z * normal;
            
            irradiance += texture(envMap, sampleVec).rgb * cos(theta) * sin(theta);
            nrSamples++;
        }
    }
    irradiance = PI * irradiance * (1.0 / float(nrSamples));
    
    imageStore(irradianceMap, ivec3(gl_GlobalInvocationID), vec4(irradiance, 1.0));
}
