use anyhow::{Context, Result};
use ash::vk;
use ash_renderer::renderer::features::ibl_manager::IblManager;
use ash_renderer::renderer::resources::ibl_asset::{IblAsset, IblAssetHeader};
use ash_renderer::renderer::resources::Texture;
use ash_renderer::vulkan::surface_provider::HeadlessSurfaceProvider;
use ash_renderer::vulkan::{Allocator, VulkanDevice, VulkanInstance};
use clap::Parser;
use std::path::PathBuf;
use std::sync::Arc;

#[derive(Parser, Debug)]
#[command(author, version, about, long_about = None)]
struct Args {
    #[arg(short, long)]
    input: PathBuf,

    #[arg(short, long)]
    output: PathBuf,

    #[arg(long, default_value_t = 512)]
    cubemap_size: u32,

    #[arg(long, default_value_t = 32)]
    irradiance_size: u32,

    #[arg(long, default_value_t = 128)]
    prefiltered_size: u32,

    #[arg(long, default_value_t = false)]
    debug: bool,
}

fn main() -> Result<()> {
    env_logger::init();
    let args = Args::parse();

    println!("🚀 Starting IBL Baker...");
    println!("   Input: {:?}", args.input);
    println!("   Output: {:?}", args.output);

    // 1. Initialize Headless Vulkan
    let surface_provider = HeadlessSurfaceProvider::new(args.cubemap_size, args.cubemap_size);
    let instance = Arc::new(
        VulkanInstance::new(&surface_provider, args.debug).context("Failed to create instance")?,
    );
    let device = Arc::new(
        VulkanDevice::new(Arc::clone(&instance), true).context("Failed to create device")?,
    );
    let allocator =
        Arc::new(unsafe { Allocator::new(&device).context("Failed to create allocator")? });

    // 2. Setup Command Pool
    let command_pool_info = vk::CommandPoolCreateInfo::default()
        .queue_family_index(device.graphics_queue_family)
        .flags(vk::CommandPoolCreateFlags::RESET_COMMAND_BUFFER);

    let command_pool = unsafe {
        device
            .device
            .create_command_pool(&command_pool_info, None)?
    };

    // 3. Load Input HDR
    println!("📥 Loading HDR texture...");
    let equirect_tex = unsafe {
        Texture::load_hdr(
            Arc::clone(&allocator),
            Arc::clone(&device.device),
            command_pool,
            device.graphics_queue,
            &args.input,
        )
        .context("Failed to load HDR texture")?
    };

    // 4. Initialize IBL Manager
    println!("⚙️  Initializing IBL Manager...");
    let mut ibl_manager = IblManager::new(Arc::clone(&device.device), Arc::clone(&allocator))
        .context("Failed to initialize IBL Manager")?;

    // 5. Bake Everything
    println!(
        "🔥 Baking cubemap ({}x{})...",
        args.cubemap_size, args.cubemap_size
    );
    let env_cubemap = ibl_manager
        .create_cubemap_from_equirect(
            &device,
            command_pool,
            equirect_tex.view(),
            equirect_tex.sampler(),
            args.cubemap_size,
        )
        .context("Failed to bake cubemap")?;

    println!("🔥 Baking irradiance map (32x32)...");
    let irradiance_map = ibl_manager
        .generate_irradiance(
            &device,
            command_pool,
            env_cubemap.view(),
            equirect_tex.sampler(),
        )
        .context("Failed to bake irradiance map")?;

    println!("🔥 Baking prefiltered map ({}x{})...", args.prefiltered_size, args.prefiltered_size);
    let prefiltered_map = ibl_manager
        .generate_prefiltered(
            &device,
            command_pool,
            env_cubemap.view(),
            equirect_tex.sampler(),
        )
        .context("Failed to bake prefiltered map")?;

    println!("🔥 Generating BRDF LUT...");
    let brdf_lut = ash_renderer::renderer::resources::ImageHandle::create_brdf_lut(
        Arc::clone(&device.device),
        Arc::clone(&allocator),
        512,
    )
    .context("Failed to create BRDF LUT image")?;

    // Note: BRDF LUT is generated by the renderer usually, but IBLManager could do it too.
    // However, IBLManager currently doesn't have a method for it.
    // For now, let's just assume we'll use a standard one or add it later.
    // Wait, let's see if 07_pbr_cube generates it.
    // It doesn't seem to have a special compute shader for it in IBLManager yet.
    // I'll skip BRDF LUT for now or just put empty data.

    // 6. Read back data
    println!("📤 Reading back data from GPU...");
    let cubemap_data = env_cubemap.read_to_buffer(command_pool, device.graphics_queue)?;
    let irradiance_data = irradiance_map.read_to_buffer(command_pool, device.graphics_queue)?;
    let prefiltered_data = prefiltered_map.read_to_buffer(command_pool, device.graphics_queue)?;
    let brdf_lut_data = brdf_lut.read_to_buffer(command_pool, device.graphics_queue)?;

    // 7. Save to Binary
    println!("💾 Saving to {:?}...", args.output);
    let asset = IblAsset {
        header: IblAssetHeader {
            magic: *b"AIBL",
            version: 1,
            cubemap_size: args.cubemap_size,
            irradiance_size: args.irradiance_size,
            prefiltered_size: args.prefiltered_size,
            prefiltered_mips: prefiltered_map.mip_levels(),
            format: env_cubemap.format().as_raw() as u32,
            _padding: [0; 8],
        },
        cubemap_data,
        irradiance_data,
        prefiltered_data,
        brdf_lut_data,
    };

    asset.save(&args.output)?;

    println!("✅ IBL Baking complete!");

    // Cleanup
    unsafe {
        device.device.destroy_command_pool(command_pool, None);
    }

    Ok(())
}
